name: Remove logs past 7 days old
on:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Prune Logs
      uses: HoseaCodes/Log-Pruner@v1.16
      with:
        mongodb_url: ${{ secrets.MONGODB_URL }}
        db_name: 'forester'
        collection_name : 'forester'
