name: forester

on: [push]

jobs:

  deploy-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2

      # - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    
      - name: Display structure of downloaded files
        run: ls -R